// Code generated by mockery v2.7.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeSampleServiceServer is an autogenerated mock type for the UnsafeSampleServiceServer type
type UnsafeSampleServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedSampleServiceServer provides a mock function with given fields:
func (_m *UnsafeSampleServiceServer) mustEmbedUnimplementedSampleServiceServer() {
	_m.Called()
}
